// // Generated by typings
// // Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/8252b2118a0b7b4c40ed3d4c3090a5c96d111420/vue-resource/index.d.ts
import "./vue";
import * as R from "./resource"

// `VueResource` in `export = VueRouter` must be a namespace
// All availanle types are exported via this namespace
declare namespace VueResource {
    export type $http = R.$http;
    export type $resource = R.$resource;
    export type Http = R.Http;
    export type Resource = R.Resource;
    export type HttpOptions = R.HttpOptions;
    export type HttpHeaders = R.HttpHeaders;
}

// TS cannot merge imported class with namespace, declare a subclass to bypass
declare class VueResource extends R.VueResource { }

export = VueResource;
